# -*- coding: utf-8 -*-
"""grapesDetector.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13AIAaAufRtDCcdqnKNFYl0TEC28txlOK
"""

!pip3 install tensorflow-gpu==1.13.1

!pip3 install keras==2.2.4

!pip3 install imageai --upgrade

!pip3 install numpy==1.16.1

!wget https://github.com/OlafenwaMoses/ImageAI/releases/download/essential-v4/pretrained-yolov3.h5

!unzip -uq "/content/drive/My Drive/grapes.zip" -d "/content/drive/My Drive"

!pip install tensorflow

!pip list

from imageai.Detection.Custom import DetectionModelTrainer

trainer = DetectionModelTrainer()
trainer.setModelTypeAsYOLOv3()
trainer.setDataDirectory(data_directory="grapes")
trainer.setTrainConfig(object_names_array=["grapes"], batch_size=8, num_experiments=50, train_from_pretrained_model="pretrained-yolov3.h5")
trainer.trainModel()

!zip -r /content/models.zip /content/grapes/models

!pip show tensorflow

!pip install tensorflow==2.2

from imageai.Detection.Custom import DetectionModelTrainer

trainer = DetectionModelTrainer()
trainer.setModelTypeAsYOLOv3()
trainer.setDataDirectory(data_directory="grapes")
trainer.evaluateModel(model_path="grapes/models", json_path="grapes/json/detection_config.json", iou_threshold=0.5, object_threshold=0.3, nms_threshold=0.5)

from imageai.Detection.Custom import CustomObjectDetection

detector = CustomObjectDetection()
detector.setModelTypeAsYOLOv3()
detector.setModelPath("grapes/models/detection_model-ex-010--loss-0013.375.h5") 
detector.setJsonPath("grapes/json/detection_config.json")
detector.loadModel()
detections = detector.detectObjectsFromImage(input_image="Screenshot(70).png", output_image_path="detected.jpg")
for detection in detections:
    print(detection["name"], " : ", detection["percentage_probability"], " : ", detection["box_points"])

from imageai.Detection.Custom import CustomVideoObjectDetection
import os
import cv2

execution_path = os.getcwd()
camera = cv2.VideoCapture(0)

video_detector = CustomVideoObjectDetection()
video_detector.setModelTypeAsYOLOv3()
video_detector.setModelPath("hololens-ex-60--loss-2.76.h5")
video_detector.setJsonPath("detection_config.json")
video_detector.loadModel()

video_detector.detectObjectsFromVideo(camera_input=camera,
                                          output_file_path=os.path.join(execution_path, "holo1-detected3"),
                                          frames_per_second=20,
                                          minimum_percentage_probability=40,
                                          log_progress=True)